### ISSUE TITLE
mum_dump.o error 1

### ISSUE THREAD

**Issue by modz2014** [zecoxao/memdump#1]
i get the error above ive tried different ways still same error

**Comment by zecoxao** [comment]
do you have latest toolchain?

**Comment by modz2014** [comment]
I'm trying to use psdkv3v for 32bit windows 7 not 64bit I think that's the problem

**Comment by zecoxao** [comment]
yes. that'd be the issue :)

**Comment by modz2014** [comment]
ill test it again soon do you have a devkit

**Comment by zecoxao** [comment]
nope

**Comment by CelesteBlue-dev** [comment]
@zecoxao You can close that issue. That is simply caused by not having taihen installed...
